In [1]:
import pandas as pd

In [4]:
transacoes = pd.read_csv("../data/transacoes.csv", sep=";")
clientes = pd.read_csv("../data/clientes.csv", sep=";")

In [3]:
transacoes.head(5)

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch

In [7]:
transacoes.rename(columns={
    "IdCliente": "idCliente"
}, inplace=True)

In [5]:
clientes.head(5)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551

In [ ]:
### join igual no sql -> a gnt parte da base que é da ESQUERDA
#merge -> join
#parte da esquerda e vai buscar na outra;
#left join
#how -> o default é o inner join (inner) (da pra usar left, right)
#on -> por qual coluna (chaves)
#colunas repetidas -> coloca x na primeira e y na segunda (da pra alterar o suffixo)
#se a coluna tiver o id diferente (nomes diferentes) ->>>

transacoes.merge(right=clientes,
                 how='left',
                 on=['idCliente'],
                 suffixes=["_transacao", "_clientes"])

,IdTransacao,idCliente,DtCriacao_transacao,QtdePontos,DescSistemaOrigem,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao_clientes,DtAtualizacao
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch,0,1,0,0,0,3380,2025-03-07 13:13:37.524,2026-05-21 13:39:35.856
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch,0,1,0,0,0,1966,2024-11-29 11:36:40.662,2025-04-28 11:33:29.687
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch,0,1,0,0,0,3143,2025-03-07 12:27:12.379,2026-05-15 14:27:29.909
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch,1,1,1,0,0,8317,2025-03-07 13:13:25.571,2026-05-22 15:15:13.179
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch,1,1,0,0,0,1610,2025-03-07 12:39:26.765,2026-05-22 14:45:22.977
...,...,...,...,...,...,...,...,...,...,...,...,...,...
322454,ffff52de-13fb-4405-a797-fddb5b4a48c5,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-24 12:22:26.313,1,twitch,1,1,0,0,0,1610,2025-03-07 12:39:26.765,2026-05-22 14:45:22.977
322455,ffffb5ab-047e-43e4-bab3-ee2d19e9b7db,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,2024-08-16 13:09:42.576,1,twitch,0,1,0,0,0,5053,2025-03-07 13:13:26.026,2026-05-18 13:13:07.091
322456,ffffc72e-d882-47f0-b933-cfd92c7e6621,2d3d2dce-d353-4961-ad39-46723efe2100,2024-02-06 11:51:24.788,1,twitch,1,1,1,0,0,1110,2025-03-07 12:40:51.664,2026-05-22 14:24:23.177
322457,ffffcd29-600c-4ae0-89b2-c62457eafc3f,c1a8d13d-cca9-4372-b195-9b0770d81a0d,2026-04-14 12:03:03.720,1,twitch,0,1,0,0,0,3341,2025-02-28 13:27:25.019,2026-05-18 13:15:34.131
322458,fffff928-9a18-4741-a516-3a92351d1d72,65662aff-44d6-4f06-b9d9-07445c6e5943,2024-08-21 14:13:31.788,1,twitch,1,1,1,0,0,8317,2025-03-07 13:13:25.571,2026-05-22 15:15:13.179

In [16]:
#quando as chaves são diferentes pra dar o join
#aqui nao vai precisar do sufixo pq nao tem colunas iguais;

df_1 = pd.DataFrame({
    "transacao": [1, 2, 3, 4, 5],
    "nome": ["t1","t2","t3","t4","t5"],
    "idcliente": [1, 2, 3, 2, 2],
    "valor": [10, 45, 32, 17, 87]
})

df_2 = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "nome": ["teo", "nah", "mah", "jose"]
})

In [17]:
df_1.merge(
    df_2,
    left_on=["idcliente"],
    right_on=["id"],
    how="left",
    suffixes=["_df1", "_df2"]
)

   transacao nome_df1  idcliente  valor  id nome_df2
0          1       t1          1     10   1      teo
1          2       t2          2     45   2      nah
2          3       t3          3     32   3      mah
3          4       t4          2     17   2      nah
4          5       t5          2     87   2      nah