## Neste projeto, trabalharemos com dois arquivos csvs separados, contendo informações sobre o preço da gasolina no Brasil.

### Link para Dataset: https://www.kaggle.com/datasets/matheusfreitag/gas-prices-in-brazil

#### 1. Carregue os conjuntos de dados \"gasolina_2000+.csv\" e \"gasolina_2010+.csv\" em dois DataFrames diferentes e combine-os em um único DataFrame.
#### 2. Investigue as colunas e entenda o conjunto de dados usando o head() e info().
#### 3. Selecione a terceira entrada da coluna DATA INICIAL e verifique seu tipo.
#### 4. Você deve ter percebido que as colunas DATA INICIAL e DATA FINAL estão formatadas como string. Utilizando o método pd.to_datetime(), converta ambas colunas para Timestamp / Datetime."
#### 5. Crie uma nova coluna para representar o ano e o mês(aaaa-mm), utilizando a coluna DATA FINAL como referência. 
#### 6. Utilizando o value_counts(), liste todos os tipos de produtos contidos na base de dados."
#### 7. Filtre o DataFrame para obter apenas dados da 'GASOLINA COMUM'. Grave em uma nova variável.
#### 8. Qual o preço médio de revenda da gasolina em agosto de 2008?
#### 9. Qual o preço médio de revenda da gasolina em maio de 2014 em São Paulo?
#### 10. Você conseguiria descobrir em qual(quais) estado(s) a gasolina ultrapassou a barreira dos R$ 5,00? E quando isso ocorreu?
#### 11. Qual a média de preço dos estados da região sul em 2012?
#### 12. Você conseguiria obter uma tabela contendo a variação percentual ano a ano para o estado do Rio de Janeiro?

In [69]:
import pandas as pd

df1 = pd.read_csv("data/gas2000+.csv", index_col=0)

In [70]:
df2 = pd.read_csv("data/gas2.csv")
df2 = df2.dropna(how='all')
df2 = df2.drop(columns=['Unnamed: 0'])
df2

C:\Users\brito\AppData\Local\Temp\ipykernel_21244\2891903346.py:1: DtypeWarning: Columns (0: MARGEM MÉDIA REVENDA, 1: PREÇO MÉDIO DISTRIBUIÇÃO, 2: DESVIO PADRÃO DISTRIBUIÇÃO, 3: PREÇO MÍNIMO DISTRIBUIÇÃO, 4: PREÇO MÁXIMO DISTRIBUIÇÃO, 5: COEF DE VARIAÇÃO DISTRIBUIÇÃO) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv("data/gas2.csv")

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2011-01-02,2011-01-08,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,2.030,0.003,2.020,2.050,0.411,0.001,1.619,0.013,1.6111,1.6411,0.008
1,2011-01-02,2011-01-08,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.717,0.102,1.490,1.990,0.225,0.059,1.492,0.069,1.3221,1.6201,0.046
2,2011-01-02,2011-01-08,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,141,R$/l,1.848,0.148,1.590,2.490,0.326,0.080,1.522,0.105,1.2833,1.7486,0.069
3,2011-01-02,2011-01-08,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,132,R$/l,1.893,0.108,1.699,2.199,0.191,0.057,1.702,0.04,1.5915,1.79,0.024
4,2011-01-02,2011-01-08,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,2.026,0.084,1.749,2.100,0.268,0.041,1.758,0.042,1.63,1.848,0.024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78180,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
78181,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
78182,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
78183,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
78184,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [71]:
df1.columns

Index(['DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO', 'PRODUTO',
       'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO'],
      dtype='str')

In [72]:
len(df2.columns.to_list())

18

In [73]:
df1.head(5)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

In [74]:
df2.columns

Index(['DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO', 'PRODUTO',
       'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO'],
      dtype='str')

In [75]:
df2.shape

(78185, 18)

In [76]:
gas_df = pd.concat([df1, df2])

In [77]:
gas_df.shape

(120823, 18)

In [78]:
gas_df.info()

<class 'pandas.DataFrame'>
Index: 120823 entries, 0 to 78184
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  str
 1   DATA FINAL                     120823 non-null  str
 2   REGIÃO                         120823 non-null  str
 3   ESTADO                         120823 non-null  str
 4   PRODUTO                        120823 non-null  str
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  str
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           120823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: float64(5), int64(1), object(6), str(6)
memory usage: 17.5+ MB

In [79]:
gas_df.head(5)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

In [80]:
gas_df.sort_values(by="DATA FINAL", ascending=True).head(3)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.35,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
43571,2004-05-09,2004-05-15,SUL,PARANA,ÓLEO DIESEL,672,R$/l,1.378,0.051,1.23,1.60,0.147,0.037,1.231,0.029,1.0029,1.309,0.024
43570,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ÓLEO DIESEL,3196,R$/l,1.368,0.057,1.21,1.59,0.158,0.042,1.21,0.026,1.141,1.369,0.021

In [81]:
type(gas_df["DATA INICIAL"].iloc[3])

str

In [82]:
gas_df["DATA INICIAL"] = pd.to_datetime(gas_df["DATA INICIAL"])
gas_df["DATA FINAL"] = pd.to_datetime(gas_df["DATA FINAL"])

In [83]:
gas_df.dtypes

DATA INICIAL                     datetime64[us]
DATA FINAL                       datetime64[us]
REGIÃO                                      str
ESTADO                                      str
PRODUTO                                     str
NÚMERO DE POSTOS PESQUISADOS              int64
UNIDADE DE MEDIDA                           str
PREÇO MÉDIO REVENDA                     float64
DESVIO PADRÃO REVENDA                   float64
PREÇO MÍNIMO REVENDA                    float64
PREÇO MÁXIMO REVENDA                    float64
MARGEM MÉDIA REVENDA                     object
COEF DE VARIAÇÃO REVENDA                float64
PREÇO MÉDIO DISTRIBUIÇÃO                 object
DESVIO PADRÃO DISTRIBUIÇÃO               object
PREÇO MÍNIMO DISTRIBUIÇÃO                object
PREÇO MÁXIMO DISTRIBUIÇÃO                object
COEF DE VARIAÇÃO DISTRIBUIÇÃO            object
dtype: object

In [84]:
### 5. Crie uma nova coluna para representar o ano e o mês(aaaa-mm)
gas_df.head(3)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098

In [85]:
gas_df["ANO"] = gas_df["DATA FINAL"].dt.year
gas_df["ANO-MES"] = gas_df["DATA FINAL"].dt.year.astype(str) + "-" + gas_df["DATA FINAL"].dt.month.astype(str).str.zfill(2)

In [86]:
gas_df.head(3)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO,ANO-MES
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,2004,2004-05
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,2004,2004-05
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,2004,2004-05

In [46]:
##6. Utilizando o value_counts(), liste todos os tipos de produtos contidos na base de dados.

gas_df["PRODUTO"].value_counts()

PRODUTO
GASOLINA COMUM        23570
GLP                   23561
ETANOL HIDRATADO      23440
ÓLEO DIESEL           21194
GNV                   14469
ÓLEO DIESEL S10        9113
OLEO DIESEL S10        2376
OLEO DIESEL            2351
GASOLINA ADITIVADA      749
Name: count, dtype: int64

In [87]:
filtro = gas_df["PRODUTO"] == "GASOLINA COMUM"
df_gas_comum = gas_df[filtro]

In [88]:
df_gas_comum.dtypes

DATA INICIAL                     datetime64[us]
DATA FINAL                       datetime64[us]
REGIÃO                                      str
ESTADO                                      str
PRODUTO                                     str
NÚMERO DE POSTOS PESQUISADOS              int64
UNIDADE DE MEDIDA                           str
PREÇO MÉDIO REVENDA                     float64
DESVIO PADRÃO REVENDA                   float64
PREÇO MÍNIMO REVENDA                    float64
PREÇO MÁXIMO REVENDA                    float64
MARGEM MÉDIA REVENDA                     object
COEF DE VARIAÇÃO REVENDA                float64
PREÇO MÉDIO DISTRIBUIÇÃO                 object
DESVIO PADRÃO DISTRIBUIÇÃO               object
PREÇO MÍNIMO DISTRIBUIÇÃO                object
PREÇO MÁXIMO DISTRIBUIÇÃO                object
COEF DE VARIAÇÃO DISTRIBUIÇÃO            object
ANO                                       int32
ANO-MES                                     str
dtype: object

In [89]:
df_gas_comum.head(3)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO,ANO-MES
12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,1.99,2.07,0.318,0.003,1.711,0.02,1.651,1.7427,0.012,2004,2004-05
12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,1.85,2.22,0.296,0.031,1.729,0.036,1.6643,1.915,0.021,2004,2004-05
12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,2.00,2.54,0.472,0.028,1.886,0.068,1.75,2.0713,0.036,2004,2004-05

In [103]:
#### 8. Qual o preço médio de revenda da gasolina em agosto de 2008?
filtro = df_gas_comum["ANO-MES"] == "2008-08"
preco_medio_revenda_agosto_2008 = df_gas_comum[filtro]["PREÇO MÉDIO REVENDA"].mean()
print(f"O preço médio de revenda da gasolia comum em agosto de 2008 foi R${preco_medio_revenda_agosto_2008:.2f}")

O preço médio de revenda da gasolia comum em agosto de 2008 foi R$2.60

In [110]:
###### 9. Qual o preço médio de revenda da gasolina em maio de 2014 em São Paulo?
filtro = (df_gas_comum["ANO-MES"] == "2014-05") & (df_gas_comum["ESTADO"] == "SAO PAULO")
preco_gasolina_sp_maio_2014 = df_gas_comum[filtro]["PREÇO MÉDIO REVENDA"].mean()
print(preco_gasolina_sp_maio_2014)

2.8822

In [ ]:
#### 10. Você conseguiria descobrir em qual(quais) estado(s) a gasolina ultrapassou a barreira dos R$ 5,00? E quando isso ocorreu?

filtro = df_gas_comum["PREÇO MÉDIO REVENDA"] > 5
df_gas_maior_que_5_reais = df_gas_comum[filtro]
df_gas_maior_que_5_reais[["ESTADO", "ANO-MES", 'PREÇO MÉDIO REVENDA']].sort_values(by="ANO-MES", ascending=False)

          ESTADO  ANO-MES  PREÇO MÉDIO REVENDA
78087  TOCANTINS  2021-05                5.751
78074       PARA  2021-05                5.447
78061       ACRE  2021-05                6.258

In [ ]:
#top estados e meses que a gasolina ficou mais cara e maior que 5 reais;

df_gas_maior_que_5_reais[["ESTADO", "ANO-MES", 'PREÇO MÉDIO REVENDA']].sort_values(by="PREÇO MÉDIO REVENDA", ascending=False).head(10)

               ESTADO  ANO-MES  PREÇO MÉDIO REVENDA
76991            ACRE  2021-03                6.688
77169            ACRE  2021-03                6.277
78061            ACRE  2021-05                6.258
77525            ACRE  2021-04                6.227
77347            ACRE  2021-04                6.220
77704            ACRE  2021-04                6.216
77882            ACRE  2021-04                6.212
77187  RIO DE JANEIRO  2021-03                6.131
77365  RIO DE JANEIRO  2021-04                6.102
78079  RIO DE JANEIRO  2021-05                6.099