In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/transacoes.csv", sep=';')

In [4]:
df.head(5)

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch

In [9]:
transacoes = df.sort_values(by="DtCriacao")

In [10]:
transacoes

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
316592,fb4e3102-6125-414e-b086-e7f641e38f93,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 11:53:23.774,1,twitch
4398,036b8d66-8adf-479b-ba0f-cb0e3207acb0,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 11:53:24.643,1,twitch
20344,10166182-a164-4608-8cdf-35e4450b2bd7,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:11:44.728,500,twitch
4613,03974c58-e86e-4b6b-8143-8f89ca870d09,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:19:41.063,1,twitch
292554,e84703a6-b606-4096-a2f3-514971c16c5c,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:31:46.288,500,twitch
...,...,...,...,...,...
106766,54f91366-56fa-49b1-a8a5-00a9fdf0b439,163022e8-12b8-486f-8604-57d8fa0ed7e1,2026-05-23 14:17:55.430,50,twitch
308877,f53158f2-88a4-40d5-b4ea-8b7af32b170d,163022e8-12b8-486f-8604-57d8fa0ed7e1,2026-05-23 14:18:11.421,50,twitch
32307,19880618-a3e6-4400-a379-207a885ce06f,ad4915a3-9308-4136-83e8-af675131ecd4,2026-05-23 14:24:52.997,-10,cursos
271759,d7bf0fe7-8bff-4b35-87c8-ac3bfcf07ccb,820c0e06-c405-4979-8975-ecfa17abb0f9,2026-05-23 14:56:39.320,50,twitch
90393,47ec9f3b-14e5-4687-bbe7-dc9ad6bfd4fa,820c0e06-c405-4979-8975-ecfa17abb0f9,2026-05-23 14:56:57.557,50,twitch

In [17]:
import pandas as pd

In [ ]:
transacoes = pd.read('../data/transacoesc.csv', sep=)